Update
MicrosoftDocs/.github pull request #48
Opened 2024-03-20 23:23 UTC by MAHEENKANNOOZ

Update

2024-03-20 23:30 UTC, MAHEENKANNOOZ reviewed
Done

2024-07-07 03:42 UTC, GO-NFT-GO reviewed
Ok

2024-07-07 03:49 UTC, GO-NFT-GO reviewed
Ok

2024-08-07 10:23 UTC, minmeun3235 requested changes

2024-08-07 10:23 UTC, minmeun3235 commented on README.md
> +Microsoft projects adopt the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.
B5690EEEBB952194

2024-08-07 10:43 UTC, minmeun3235 approved these changes

2024-08-07 10:43 UTC, minmeun3235 commented on README.md
> +Microsoft projects adopt the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.
B5690EEEBB952194### ### [](url)

2024-09-16 12:33 UTC, secureinvestment approved these changes
MAHEENKANNOOZ:main

2024-09-16 12:35 UTC, secureinvestment approved these changes
.github/workflows/blank.yml

2024-09-16 12:39 UTC, secureinvestment reviewed
MAHEENKANNOOZ:main

2024-10-26 00:01 UTC, Andreelysenko approved these changes

2026-08-19 21:23 UTC, closed without merging